import datetime

from models import Client, PlanEnum

SOUTH_AMERICA = 'South America'
continent_contry_city_list = [
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Paulo'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Rio de Janeiro'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Belo Horizonte'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Brasília'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Salvador'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Fortaleza'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Manaus'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Curitiba'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Recife'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Porto Alegre'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Belém'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Goiânia'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Guarulhos'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Campinas'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Luís'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Gonçalo'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Maceió'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Duque de Caxias'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Natal'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Teresina'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Bernardo do Campo'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Nova Iguaçu'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São José dos Campos'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Santo André'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'João Pessoa'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Jaboatão dos Guararapes'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Osasco'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Ribeirão Preto'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Uberlândia'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Sorocaba'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Contagem'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Aracaju'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Rosario'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Buenos Aires'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Córdoba'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Rosario'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Mendoza'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'La Plata'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Miguel de Tucumán'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Mar del Plata'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Salta'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Santa Fe'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Juan'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Resistencia'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Neuquén'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Corrientes'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Salvador de Jujuy'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Posadas'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Formosa'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Fernando del Valle de Catamarca'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Luis'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'La Rioja'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Río Gallegos'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Ushuaia'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Medellín'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Bogotá'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Cali'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Barranquilla'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Cartagena'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Cúcuta'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Soledad'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Ibagué'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Bucaramanga'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Soacha'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Santa Marta'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Villavicencio'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Bello'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Pereira'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Valledupar'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Montería'},
]

time_list = [
    {'id': 100, 'hour': 1, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 200, 'hour': 2, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 300, 'hour': 3, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 400, 'hour': 4, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 500, 'hour': 5, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 600, 'hour': 6, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 700, 'hour': 7, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 800, 'hour': 8, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 900, 'hour': 9, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 1000, 'hour': 10, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 1100, 'hour': 11, 'minute': 0, 'part_of_day': 'Morning'},
    {'id': 1200, 'hour': 12, 'minute': 0, 'part_of_day': 'Midday'},
    {'id': 1300, 'hour': 13, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1300, 'hour': 13, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1400, 'hour': 14, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1500, 'hour': 15, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1600, 'hour': 16, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1700, 'hour': 17, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1800, 'hour': 18, 'minute': 0, 'part_of_day': 'Afternoon'},
    {'id': 1900, 'hour': 19, 'minute': 0, 'part_of_day': 'Night'},
    {'id': 2000, 'hour': 20, 'minute': 0, 'part_of_day': 'Night'},
    {'id': 2100, 'hour': 21, 'minute': 0, 'part_of_day': 'Night'},
    {'id': 2200, 'hour': 22, 'minute': 0, 'part_of_day': 'Night'},
    {'id': 2300, 'hour': 23, 'minute': 0, 'part_of_day': 'Night'},
    {'id': 2400, 'hour': 0, 'minute': 0, 'part_of_day': 'Night'},
]

ages_list = [
    '20-29',
    '30-39',
    '40-49',
    '50-59',
    '60-69',
    '70+',
]

client_list = [
    Client(
        id='acfa53b4-58f3-46e8-809b-19ef52b437ed',
        name='Universo Móvel',
        plan=PlanEnum.EMPRENDEDOR.value,
        initial_date=datetime.date(2024, 10, 10),
        final_date=datetime.date(2099, 1, 1),
    ),
    Client(
        id='22128c04-0c2c-4633-8317-0fffd552f7a6',
        name='GlobalCom',
        plan=PlanEnum.EMPRESARIO.value,
        initial_date=datetime.date(2024, 9, 15),
        final_date=datetime.date(2099, 1, 1),
    ),
    Client(
        id='9a652818-342e-4771-84cf-39c20a29264d',
        name='GigaTel',
        plan=PlanEnum.EMPRESARIO_PLUS.value,
        initial_date=datetime.date(2024, 8, 27),
        final_date=datetime.date(2099, 1, 1),
    ),
]
