SOUTH_AMERICA = 'South America'
continent_contry_city_list = [
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Paulo'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Rio de Janeiro'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Belo Horizonte'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Brasília'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Salvador'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Fortaleza'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Manaus'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Curitiba'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Recife'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Porto Alegre'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Belém'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Goiânia'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Guarulhos'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Campinas'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Luís'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Gonçalo'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Maceió'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Duque de Caxias'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Natal'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Teresina'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São Bernardo do Campo'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Nova Iguaçu'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'São José dos Campos'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Santo André'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'João Pessoa'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Jaboatão dos Guararapes'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Osasco'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Ribeirão Preto'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Uberlândia'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Sorocaba'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Contagem'},
    {'continent': SOUTH_AMERICA, 'country': 'Brazil', 'city': 'Aracaju'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Rosario'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Buenos Aires'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Córdoba'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Rosario'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Mendoza'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'La Plata'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Miguel de Tucumán'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Mar del Plata'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Salta'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Santa Fe'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Juan'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Resistencia'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Neuquén'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Corrientes'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Salvador de Jujuy'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Posadas'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Formosa'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Fernando del Valle de Catamarca'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'San Luis'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'La Rioja'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Río Gallegos'},
    {'continent': SOUTH_AMERICA, 'country': 'Argentina', 'city': 'Ushuaia'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Medellín'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Bogotá'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Cali'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Barranquilla'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Cartagena'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Cúcuta'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Soledad'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Ibagué'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Bucaramanga'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Soacha'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Santa Marta'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Villavicencio'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Bello'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Pereira'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Valledupar'},
    {'continent': SOUTH_AMERICA, 'country': 'Colombia', 'city': 'Montería'},
]
